name: MultiUser
on:
  workflow_dispatch:
     inputs:
      githubrepo:
        description: 'GitRepoName'     
        required: true
        default: 'Provide the GitReponame'
          
jobs:
  repoaccess:
    runs-on: ubuntu-latest
    steps:
    - name: creating github repo
      run: |   
           echo ${{ secrets.SELFSERVICE_GITHUB_TOKEN }} | gh auth login --with-token
           gh api --method=PUT "repos/teja-5/${{ github.event.inputs.githubrepo }}/collaborators/teja -f permission=write
