name: sentinvitation
on:
  workflow_dispatch:
     inputs:
      emailid:
        description: 'emailID'     
        required: true
        default: 'provide your teja email id'
          
jobs:
  sentinvitation:
    runs-on: ubuntu-latest
    steps:
    - name: creating github repo
      run: |   
           emailid=${{ github.event.inputs.emailid }}
           emaildomain=$(echo $emailid | cut -d "@" -f 2)
           if [[ $emaildomain == "teja.com" ]]; then
              echo "${{ github.event.inputs.emailid }} is teja emailid"
              curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.SELFSERVICE_GITHUB_TOKEN }}"\
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/orgs/teja-5/invitations \
                -d '{"email":"${{ github.event.inputs.emailid }}","role":"direct_member"}'
           else
              echo "the emailid is not teja email id"
           fi
