name: rdsupdownscale
on:
  workflow_dispatch:
     inputs:
      database_name:
        description: 'RDS db instance'     
        required: true
        default: 'Provide RDS DB Name' 
      desired_db_size:
        description: 'DB_Size'     
        required: true
        default: 'db.t3.micro'
            
jobs:
  upscale:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: upscale cluster
      run: |   
            chmod +x ./rdsupdownscale.sh
            ./rdsupdownscale.sh  "${{ github.event.inputs.database_name }}" "${{ github.event.inputs.desired_db_size }}" 
      shell: bash
      
